/**
 * This file was auto generated by packages/playground/wordpress-builds/build/build.js
 * DO NOT CHANGE MANUALLY!
 * This file must statically exists in the project because of the way
 * vite resolves imports.
 */
export declare function getWordPressModuleDetails(wpVersion?: string): {
    size: number;
    url: string;
};
